{
 "title": "SFCNC01",
 "description": "sfcnc01 monitoring screen",
 "tags": [ "CNC" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Spindle Speed",
   "type": "timeseries",
   "description": "Spindle Speed over time",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "dataset": "sfcncpool",
     "rawSql": "SELECT Timestamp, SpindleSpeed FROM sfcncpool.sfcnc01 ORDER BY Timestamp DESC LIMIT 1000 "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "dataset": "sfcncpool",
     "rawSql": "SELECT RunStatus, EmergencyStop, ActiveAlarms FROM sfcncpool.sfcnc01 ORDER BY Timestamp DESC LIMIT 1 "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": " \r\n SELECT M30Counter1, M30Counter2, Mode, Program FROM sfcncpool.sfcnc01 ORDER BY Timestamp DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Runtime Remainng",
   "type": "timeseries",
   "description": "runtime remaining for sfcnc01",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "sfcncpool",
     "rawSql": "SELECT Timestamp, CycleRemainingTime FROM sfcncpool.sfcnc01 ORDER BY Timestamp DESC LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sfcncpool",
     "rawSql": "SELECT MachineRunTime FROM sfcncpool.sfcnc01 ORDER BY Timestamp DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sfcncpool",
     "rawSql": "SELECT Timestamp, ThisCycle, CycleRemainingTime FROM sfcncpool.sfcnc01 ORDER BY Timestamp DESC LIMIT 1000 "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "options": {
    "content": "\n<div style=\"text-align: center;\">\n  <img src=\"http://sfgrafana.sf.local/Full_Transparent_Background.png\" alt=\"WSU Tech - Smart Factory\" style=\"max-width: 100%; max-height: 100%;\">\n</div>\n\n"
   },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sfcncpool",
     "rawSql": "SELECT Timestamp, SpindleSpeed, FeedrateOverride, RapidOverride, SpindleSpeedOverride FROM sfcncpool.sfcnc01 ORDER BY Timestamp DESC LIMIT 1000 "
    }
   ]
  }
 ]
}